{% set name = "pylsl" %}
{% set version = "1.13.0.b3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} setup.py -v install"
  noarch: python

requirements:
  host:
    - python
    - liblsl
  run:
    - python
    - liblsl

test:
  commands:
    - python -c 'import pylsl; print(pylsl.pylsl.library_info());'

about:
  home: https://github.com/labstreaminglayer/liblsl-Python
  license: MIT
  license_family: MIT
  license_file: 
  summary: Python interface to the Lab Streaming Layer
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - tstenner
